[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pathlib",
    "setuptools-git-versioning"
]

build-backend = "setuptools.build_meta"
[tool.setuptools-git-versioning]
enabled = true