"""add_testcase

Revision ID: 14b6046be217
Revises: 4a78159af963
Create Date: 2022-03-25 14:33:40.866340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14b6046be217'
down_revision = '4a78159af963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('update_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('create_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('testsuite', sa.Column('testplans', postgresql.ARRAY(postgresql.UUID(as_uuid=True), as_tuple=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testsuite', 'testplans')
    op.drop_table('testplan')
    # ### end Alembic commands ###
